name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14
        env:
          POSTGRES_DB: carna-database
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U urbano" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install backend dependencies
        working-directory: backend
        run: |
          yarn install --frozen-lockfile
          yarn add --dev wait-on

      - name: Run backend unit tests
        working-directory: backend
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_USER: postgres
          DATABASE_PASSWORD: 1234
          DATABASE_NAME: carna-database
        run: yarn test

      - name: Start backend server
        working-directory: backend
        run: yarn start > backend.log 2>&1 &

      - name: Show backend logs
        run: cat backend/backend.log || true

      - name: Wait for backend to be ready
        run: npx wait-on http://localhost:5000/api/v1/health

      - name: Run backend e2e tests
        working-directory: backend
        run: yarn test:e2e

      - name: Install frontend dependencies
        working-directory: frontend
        run: yarn install --frozen-lockfile

      - name: Run frontend tests
        working-directory: frontend
        run: yarn test

      - name: Build backend
        working-directory: backend
        run: yarn build

      - name: Build frontend
        working-directory: frontend
        run: yarn build
